## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Caernarfon,GB,53.1413,-4.2702,60.71,40,90,25.32,overcast clouds
1,1,George Town,MY,5.4112,100.3354,82.33,78,20,2.30,few clouds
2,2,Aldan,RU,58.6031,125.3894,29.91,97,100,10.96,snow
3,3,Partizanskoye,RU,55.5006,94.3900,47.12,51,100,21.99,overcast clouds
4,4,San Andres,CO,12.5847,-81.7006,84.22,74,20,8.05,few clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp=float(input("What is the minimum temperature you would like for your trip? "))
max_temp=float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"]<=max_temp)&(city_data_df["Max Temp"]>=min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,George Town,MY,5.4112,100.3354,82.33,78,20,2.30,few clouds
4,4,San Andres,CO,12.5847,-81.7006,84.22,74,20,8.05,few clouds
7,7,Auki,SB,-8.7676,160.7034,88.00,60,89,4.88,overcast clouds
8,8,Atuona,PF,-9.8000,-139.0333,77.72,68,4,13.20,clear sky
15,15,Bengkulu,ID,-3.8004,102.2655,75.56,91,100,10.49,overcast clouds
25,25,Caravelas,BR,-17.7125,-39.2481,75.31,82,9,6.42,clear sky
26,26,Bima,ID,-8.4667,118.7167,89.46,57,100,2.17,overcast clouds
34,34,Bilma,NE,18.6853,12.9164,79.23,16,0,4.72,clear sky
35,35,Kapaa,US,22.0752,-159.3190,82.38,72,1,5.01,clear sky
38,38,Flinders,AU,-34.5833,150.8552,76.80,68,3,7.00,clear sky

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [9]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df=preferred_cities_df
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,George Town,MY,5.4112,100.3354,82.33,78,20,2.30,few clouds
4,4,San Andres,CO,12.5847,-81.7006,84.22,74,20,8.05,few clouds
7,7,Auki,SB,-8.7676,160.7034,88.00,60,89,4.88,overcast clouds
8,8,Atuona,PF,-9.8000,-139.0333,77.72,68,4,13.20,clear sky
15,15,Bengkulu,ID,-3.8004,102.2655,75.56,91,100,10.49,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
673,673,Ulladulla,AU,-35.3500,150.4667,76.77,46,5,7.56,clear sky
680,680,Lucea,JM,18.4510,-78.1736,80.46,79,10,4.85,clear sky
683,683,Guarapari,BR,-20.6667,-40.4975,75.09,95,100,6.20,overcast clouds
688,688,Ternate,ID,0.8000,127.4000,84.67,68,12,0.60,few clouds
690,690,Rabaul,PG,-4.1967,152.1721,85.24,67,20,6.78,few clouds

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,George Town,MY,82.33,few clouds,5.4112,100.3354,
4,San Andres,CO,84.22,few clouds,12.5847,-81.7006,
7,Auki,SB,88.00,overcast clouds,-8.7676,160.7034,
8,Atuona,PF,77.72,clear sky,-9.8000,-139.0333,
15,Bengkulu,ID,75.56,overcast clouds,-3.8004,102.2655,
25,Caravelas,BR,75.31,clear sky,-17.7125,-39.2481,
26,Bima,ID,89.46,overcast clouds,-8.4667,118.7167,
34,Bilma,NE,79.23,clear sky,18.6853,12.9164,
35,Kapaa,US,82.38,clear sky,22.0752,-159.3190,
38,Flinders,AU,76.80,clear sky,-34.5833,150.8552,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping.")
        
hotel_df.head(10)

Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,George Town,MY,82.33,few clouds,5.4112,100.3354,Cititel Penang
4,San Andres,CO,84.22,few clouds,12.5847,-81.7006,Hotel Arena Blanca
7,Auki,SB,88.00,overcast clouds,-8.7676,160.7034,Auki Motel
8,Atuona,PF,77.72,clear sky,-9.8000,-139.0333,Villa Enata
15,Bengkulu,ID,75.56,overcast clouds,-3.8004,102.2655,Grage Hotel Bengkulu
25,Caravelas,BR,75.31,clear sky,-17.7125,-39.2481,Pousada dos Navegantes
26,Bima,ID,89.46,overcast clouds,-8.4667,118.7167,Lambitu Hotel
34,Bilma,NE,79.23,clear sky,18.6853,12.9164,Expeditions Ténére voyages
35,Kapaa,US,82.38,clear sky,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
38,Flinders,AU,76.80,clear sky,-34.5833,150.8552,Shellharbour Resort & Conference Centre

In [32]:
# 7. Drop the rows where there is no Hotel Name.
import numpy as np
hotel_df['Hotel Name'].replace('', np.nan, inplace=True)
hotel_df.tail(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
634,Akyab,MM,77.68,broken clouds,20.1500,92.9000,Hotel Memory
635,Oussouye,SN,78.98,overcast clouds,12.4850,-16.5469,Auberge du Routard
636,Swan Hill,AU,81.79,scattered clouds,-35.3378,143.5544,Lazy River Motor Inn
637,Dhidhdhoo,MV,81.45,overcast clouds,6.8833,73.1000,Dhidhoo beach
640,Angoche,MZ,76.24,few clouds,-16.2325,39.9086,Guest House HESADA
650,Cayenne,GF,81.09,few clouds,4.9333,-52.3333,Hôtel Le Dronmi
652,Boa Viagem,BR,77.74,scattered clouds,-5.1275,-39.7322,Inn and Steakhouse Aconchego
653,Mopti,ML,87.30,broken clouds,14.6667,-4.0000,NaN
655,Nkhotakota,MW,77.13,clear sky,-12.9274,34.2961,Sitima Inn
657,Kiunga,PG,87.96,overcast clouds,-6.1219,141.2906,Airport Lodge Kiunga
660,Kirakira,SB,84.76,overcast clouds,-10.4544,161.9205,SanBiz Lodge
662,Vanimo,PG,84.43,overcast clouds,-2.6741,141.3028,Vahmoneh Lodge Vanimo
665,Sagua La Grande,CU,77.99,overcast clouds,22.8067,-80.0756,Hotel Telégrafo
667,Laje,BR,75.81,scattered clouds,-10.1833,-40.9667,NN Pousada
669,Prainha,BR,78.53,scattered clouds,-1.8000,-53.4800,Casa Rocha
673,Ulladulla,AU,76.77,clear sky,-35.3500,150.4667,Sandpiper Motel
680,Lucea,JM,80.46,clear sky,18.4510,-78.1736,Grand Palladium Jamaica Resort & Spa
683,Guarapari,BR,75.09,overcast clouds,-20.6667,-40.4975,Hotel Porto do Sol
688,Ternate,ID,84.67,few clouds,0.8000,127.4000,Grand Dafam Bela Ternate
690,Rabaul,PG,85.24,few clouds,-4.1967,152.1721,Rabaul Hotel

In [38]:
clean_hotel_df=hotel_df.dropna()
clean_hotel_df.tail(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
628,Veraval,IN,77.58,clear sky,20.9000,70.3667,Lords Inn Somnath
634,Akyab,MM,77.68,broken clouds,20.1500,92.9000,Hotel Memory
635,Oussouye,SN,78.98,overcast clouds,12.4850,-16.5469,Auberge du Routard
636,Swan Hill,AU,81.79,scattered clouds,-35.3378,143.5544,Lazy River Motor Inn
637,Dhidhdhoo,MV,81.45,overcast clouds,6.8833,73.1000,Dhidhoo beach
640,Angoche,MZ,76.24,few clouds,-16.2325,39.9086,Guest House HESADA
650,Cayenne,GF,81.09,few clouds,4.9333,-52.3333,Hôtel Le Dronmi
652,Boa Viagem,BR,77.74,scattered clouds,-5.1275,-39.7322,Inn and Steakhouse Aconchego
655,Nkhotakota,MW,77.13,clear sky,-12.9274,34.2961,Sitima Inn
657,Kiunga,PG,87.96,overcast clouds,-6.1219,141.2906,Airport Lodge Kiunga
660,Kirakira,SB,84.76,overcast clouds,-10.4544,161.9205,SanBiz Lodge
662,Vanimo,PG,84.43,overcast clouds,-2.6741,141.3028,Vahmoneh Lodge Vanimo
665,Sagua La Grande,CU,77.99,overcast clouds,22.8067,-80.0756,Hotel Telégrafo
667,Laje,BR,75.81,scattered clouds,-10.1833,-40.9667,NN Pousada
669,Prainha,BR,78.53,scattered clouds,-1.8000,-53.4800,Casa Rocha
673,Ulladulla,AU,76.77,clear sky,-35.3500,150.4667,Sandpiper Motel
680,Lucea,JM,80.46,clear sky,18.4510,-78.1736,Grand Palladium Jamaica Resort & Spa
683,Guarapari,BR,75.09,overcast clouds,-20.6667,-40.4975,Hotel Porto do Sol
688,Ternate,ID,84.67,few clouds,0.8000,127.4000,Grand Dafam Bela Ternate
690,Rabaul,PG,85.24,few clouds,-4.1967,152.1721,Rabaul Hotel

In [40]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [51]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [52]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))